using System.ComponentModel.DataAnnotations.Schema;

namespace TaskManagerWebsite.Models;

/// <summary>
/// Represents an administrative entity in the system.
/// This class links an admin to a specific user.
/// </summary>
public class Admin
{
    /// <summary>
    /// Gets or sets the unique identifier for the admin.
    /// This value is auto-generated by the database.
    /// </summary>
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    /// <summary>
    /// Gets or sets the user ID associated with the admin.
    /// </summary>
    public int UserId { get; set; }

    /// <summary>
    /// Navigation property for the associated user entity.
    /// </summary>
    public virtual User User { get; set; }
}